### Feature Pay — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllPays
GET {{baseUrl}}/api/pagos

###

# @name getOnePay
GET {{baseUrl}}/api/pagos/{{id}}
