### Feature Owner — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllOwners
GET {{baseUrl}}/api/propietarios

###

# @name getOneOwner
GET {{baseUrl}}/api/propietarios/{{id}}
